components/Mappings/Mappings.js
components/Mappings/NewFieldModal.js

Removed `react-select`, `rc-tooltip` & `font awesome` Icons from Mappings View

Add antd dropdown, tooltip & Icon in Mappings View

---

components/SearchSandbox/index.js
components/SearchSandbox/template.js

Removed the `message` prop , created `attribution` prop to show in Sandbox

Dejavulogo

---

components/SearchSandbox/components/RSWrapper.js
components/SearchSandbox/containers/Editor.js
components/SearchSandbox/index.js

Usage
```js
customProps={{
ReactiveList: {
onData: res => (
<div style={{ background: 'aqua' }}>{JSON.stringify(res)}</div>
),
style: { background: 'red' },
},
DataSearch: {
renderSuggestions: res => (
<div style={{ background: 'yellow' }}>{JSON.stringify(res)}</div>
),
},
}}
```

Custom props

---

components/SearchSandbox/components/PreviewList.js

Fix : Replace height with maxHeight

---

components/SearchSandbox/components/RSWrapper.js

When adding a new field the default weight will be 1

Minor fix to change default weight to 1

---

components/SearchSandbox/containers/Editor.js
components/SearchSandbox/index.js

Usage:
```js
<SearchSandbox isPlugin />
```

Add isPlugin prop

---

components/SearchSandbox/components/Header.js
components/SearchSandbox/components/RSWrapper.js
components/SearchSandbox/index.js

```js
showCodePreview = { false } // Hides Code preview Button
showCustomList = { false } // Hides Custom List Button
showProfileOption = { false } // Hides Profile List Dropdown
```
If `showProfileOption` & `showCodeSandbox` both are false than do not render `Header` Component

Introduce props for code preview, custom List and profile option

---

components/Mappings/ErrorModal.js
components/Mappings/Mappings.js
components/Mappings/NewFieldModal.js
components/Mappings/styles.js

**Changes**
- Antd Button
- Antd Modal
- Antd Input and Dropdown
**Demo**

New design

---

components/shared/UpgradePlan/Banner.js

Required in - https://github.com/appbaseio/dashboard/pull/125

 Add prop to hide button in Banner

---

components/SearchSandbox/index.js
components/SearchSandbox/utils/joyrideSteps.js
components/shared/Walkthrough.js
utils/joyrideSteps.js

**Changes**
- Add Credential Page Walkthrough Steps
- Add edge case which might help prevent breaking in future

Add joyride steps for Credentials page

---

components/SearchSandbox/components/PreviewList.js
components/SearchSandbox/components/RenderResults.js
utils/index.js

Fix image styling in search preview

---

components/SearchSandbox/components/PreviewList.js
components/SearchSandbox/index.js
components/SearchSandbox/utils/getComponentProps.js

Generated Code: 
CodeSandbox:
With Custom List: https://codesandbox.io/s/l9z37j0koz
With Tree View: https://codesandbox.io/s/531w997olx
Dashboard ReactiveList Props:

Update RS version

---

components/SearchSandbox/components/RSWrapper.js
components/SearchSandbox/styles.js
components/SearchSandbox/utils/getComponentProps.js

Current MultiList:
After using `renderItem` & custom styles:

Use renderItem in MultiList

---

components/Mappings/Mappings.js
utils/mappings.js

Preview Card:
Modal For updating:

Add option to change number of Shards

---

components/SearchSandbox/containers/Editor.js
components/SearchSandbox/styles.js

Have tested with Movies & Shopify app.

Use custom selected Filters for rendering html

---

components/Mappings/Mappings.js
components/SearchSandbox/index.js
utils/mappings.js
utils/sandbox.js

- Fix reindex Body
- Hide Profile Option

Arc: Fix reindex request body & preferences

---

components/Mappings/Mappings.js

- Update synonyms
- Fetch setting before Reindex 
- Fetch updated mappings according to analyzer before Reindex

Fix synonyms working

---

components/Mappings/Mappings.js
components/SearchSandbox/containers/Editor.js
components/SearchSandbox/styles.js

Update Arc branch

---

components/analytics/components/Summary/SummaryCard.js

fix: summary stats and formatting of analytics number

---

components/analytics/components/Filter/index.js

Bug Fix: https://www.loom.com/share/3dabffeedc164ab5b8a0e4b936241306
https://www.loom.com/share/3fa2a9eb2cc34ff494deabbbb1a91a86

fix: clear filter value

---

components/analytics/components/Summary/SummaryCard.js
components/analytics/components/Summary/index.js

feat: display avg. click position

---

components/analytics/components/Filter/index.js

When we clear all the filter options remain intact and we need to refresh to remove that filter options.
https://www.loom.com/share/5f6e8fd8ae30455f9776f10cc66867c8
Filter Component in Analytics

fix(analytics): make filter input controlled and sync with redux state

---

components/analytics/components/Filter/index.js

Reverts appbaseio/batteries#223

Revert "fix(analytics): make filter input controlled and sync with redux state"

---

components/BaseContainer/index.js
components/analytics/components/Analytics.js
components/analytics/components/Filter/index.js
components/analytics/components/RequestDistribution/index.js
components/analytics/components/RequestLogs/index.js
components/analytics/components/SearchLatency/index.js
components/analytics/components/Summary/index.js
components/analytics/utils.js
utils/helpers.js

Releated PR https://github.com/appbaseio-confidential/arc-dashboard/pull/217

feat: add search logs in latency view

---

utils/mappings.js

Merge this after this PR is merged: https://github.com/appbaseio-confidential/arc-dashboard/pull/236

fix: remove n-gram changes from reindex

---

components/Monitoring/GraphToolTip.js

https://www.loom.com/share/560018ab1edd407491fa763a36f30006?from_recorder=1

fix: add fallback for undefined graph data

---

components/analytics/utils.js

- replay request function updated to ignore some additional headers
- toaster messages updated in utils

fix: replay request function and toaster messages updated in utils

---

components/SearchSandbox/containers/AceEditor.js
components/analytics/components/RequestLogs/RequestDetails.js
components/analytics/components/RequestLogs/index.js
components/analytics/utils.js

Updated PR - https://github.com/appbaseio/batteries/pull/265
- sentry issue with the request logs in arc-dashboard
- look into this PR for further reference - https://github.com/appbaseio-confidential/arc-dashboard/pull/350
- demo - https://www.loom.com/share/7c89a752b2f04d7e9822d9a2b1f3f1bc

updated parsing logic for request logs

---

components/shared/UpgradePlan/Banner.js

Fix Banner in search settings with flex !important.

fix: search settings banner

---

components/Mappings/Mappings.js

EnableNgram and enableAutoSuggestion changes

EnableNgram and enableAutoSuggestion changes

---

modules/actions/rules.js

**PR Type** 🐞  `BugFix`
**Description** support for FE arc-dashboard fixes.
[📔  Notion](https://www.notion.so/appbase/Arc-dashboard-FE-issues-ccd20fd743e64fc28e2bbb1ee519cf32)
https://github.com/appbaseio-confidential/arc-dashboard/pull/452

fix: frontend bugs

---

utils/app.js
utils/index.js
utils/requestService.js

Depending PR - https://github.com/appbaseio-confidential/arc-dashboard/pull/576

feat: add util method to change search backend

---

modules/actions/app.js

feat: fallback for url in mappings api

---

modules/reducers/getAppSearchBoxes.js

fix - have a loading state when updating a searchbox

fix: loading state of updating searchbox

---

modules/actions/pipelines.js
modules/reducers/getAppPipelines.js
utils/app.js

**PR Type** `feat`
**Description** The PR modifies the actions and reducers to fetch scriptRefs by version ID.
[📔  Notion](https://www.notion.so/reactivesearch/scriptRef-change-for-fetching-versioned-scriptRef-1b864a0f5aa54f7c94efb5238af6d82c) 
https://github.com/appbaseio-confidential/arc-dashboard/pull/608

feat: get scripts by version id

---

utils/index.js

**PR Type** `feature` ⭐ 
**Description** The PR adds `marklogic` as a supported backend for the arc-dashboard.
https://github.com/appbaseio-confidential/arc-dashboard/pull/609

 feat: add marklogic as a supported backend

---

components/Mappings/Mappings.js
components/Mappings/NewFieldModal.js
components/Mappings/Synonyms.js
components/Monitoring/Indices.js
components/Monitoring/MonitoringContainer.js
components/Monitoring/NodeGraphs.js
components/Monitoring/NodeStats.js
components/Monitoring/NodeSummary.js
components/Monitoring/Overview.js
components/SearchSandbox/components/DataFieldInput.js
components/SearchSandbox/components/DeleteJSON.js
components/SearchSandbox/components/EditorJSON.js
components/SearchSandbox/components/Header.js
components/SearchSandbox/components/PreviewList.js
components/SearchSandbox/components/RSWrapper.js
components/SearchSandbox/components/RenderResults.js
components/SearchSandbox/containers/Editor.js
components/analytics/components/Analytics.js
components/analytics/components/RequestLogs/index.js
components/analytics/components/Searches.js
components/analytics/components/Summary/SummaryCard.js
components/analytics/utils.js
components/shared/Overlay.js
components/shared/UpgradePlan/Banner.js
components/shared/Walkthrough.js

fix: antd v4 upgrade

---

components/Mappings/ErrorModal.js
components/Mappings/Mappings.js
components/Mappings/NewFieldModal.js
components/Mappings/Synonyms.js
components/SearchSandbox/components/DataFieldInput.js
components/SearchSandbox/components/EditorJSON.js
components/SearchSandbox/components/Header.js
components/SearchSandbox/components/PreviewList.js
components/SearchSandbox/components/RSWrapper.js
components/SearchSandbox/containers/Editor.js
components/analytics/components/RequestDistribution/index.js
components/analytics/components/RequestLogs/RequestDetails.js
components/analytics/utils.js
utils/monitoring.js

feat: migrate antd to v5

---

modules/actions/app.js

Fix field selector not working.

fix: issues for cypress tests

---

components/SearchSandbox/components/RSWrapper.js
components/SearchSandbox/containers/Editor.js
components/SearchSandbox/styles.js

Search preview form layout fix
supports https://github.com/appbaseio/dejavu/pull/457

fix: forms in search preview

---

modules/actions/account.js
utils/index.js
utils/monitoring.js

Supports https://github.com/appbaseio/dashboard/pull/500

fix: staging URL

---

modules/actions/account.js
utils/index.js

* Update staging flag and production URL

Test auth0

---

components/analytics/components/RequestLogs/index.js

The PR addresses routing issue with app level request logs. 
Issue reported -
https://www.loom.com/share/db48166f39df4d40beb68f19cb061d2b

fix: request logs routing

---

components/shared/VersionController/index.js

**PR Type**
The PR bypasses version controller check for sls image type
Dependent PR
---
https://github.com/appbaseio-confidential/arc-dashboard/pull/670

bypass version controller check for sls image type

---

utils/app.js
utils/index.js

supports https://github.com/appbaseio-confidential/arc-dashboard/pull/685

add API utils to get/ POST AI preferences

---

utils/helpers.js

[Arc-dashboard PR](https://github.com/appbaseio-confidential/arc-dashboard/pull/704)
Persist execution context.

feat: update execution context
